# A universal template to ingest data from any source
artifacts_root: artifacts



data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/blahblahblah1920/Random-data/raw/main/archive%20(7).zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion