# A universal template to ingest data from any source
artifacts_root: artifacts



data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/blahblahblah1920/Random-data/raw/main/archive%20(7).zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5